### ISSUE TITLE
When no Role is assigned the userinfo fails

### ISSUE THREAD

**Issue by Highom** [NTMNathan/djs-class-handler#54]
In the name attribute field you show the cache size with -1 but then in the if statement for the value you just check the cache size without substracting 1. I added the substraction to the code locally and this fixed the issue for me. 

> {
>   name: `📝 Roles [${member.roles.cache.size - 1}]`,
>   value: member.roles.cache.size - 1 ? member.roles.cache.map(roles => `**${roles}**`).slice(0, -1).join(' ') : 'None',
>   inline: false,
> },

**Comment by NTMNathan** [comment]
Fixed!
